name: RisingOS Builder

on:
  workflow_dispatch:
    inputs:
      BRAND:
        description: 'Put your device manufacturer name please.'
        required: true
      CODENAME:
        description: 'Put your device codename please.'
        required: true
      SIGNING:
        description: 'The build signing. Set to "normal" by default.'
        required: true
        default: 'normal'
        type: choice
        options:
          - 'full'
          - 'normal'
          - 'normal-fastboot'
      TYPE:
        description: 'The build type. Set to "userdebug" by default.'
        required: true
        default: 'userdebug'
        type: choice
        options:
          - 'eng'
          - 'user'
          - 'userdebug'
      RELEASE:
        description: 'The build target. Set to "stable" by default.'
        required: true
        default: 'stable'
        type: choice
        options:
          - 'test'
          - 'stable'

run-name: "RisingOS Build: ${{ inputs.BRAND }} ${{ inputs.CODENAME }} [${{ inputs.TYPE }}, ${{ inputs.RELEASE }}]"

jobs:
  build:
    env:
      USER: sketu
      BRAND: ${{ inputs.BRAND }}
      CODENAME: ${{ inputs.CODENAME }}
      SIGNING: ${{ inputs.SIGNING }}
      TYPE: ${{ inputs.TYPE }}
      RELEASE: ${{ inputs.RELEASE }}
      GH_TOKEN: ${{ secrets.TOKEN }}

    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      #- name: Init and Sync
        #run: sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ env.USER }}@${{ secrets.IP }}" 'cd /home/sketu/rising && bash init.sh'
        #continue-on-error: true

      - name: Clone Repositories
        run: bash clone.sh

      - name: Build RisingOS
        run: bash build.sh
            
      - name: Check and Upload Build Artifacts
        run: |
          if [ -s "/home/sketu/rising/out/error.log" ] || [ -s "/home/sketu/rising/out/target/product/${CODENAME}/*${CODENAME}.json" ]; then
            echo "Uploading build logs..."
            gh run upload-artifact --name build-logs /home/sketu/rising/out/error.log /home/sketu/rising/out/target/product/${CODENAME}/*${CODENAME}.json
          else
            echo "No non-empty files to upload."
          fi

      - name: Upload Build Files
        run: bash upload.sh

      - name: Post-Cleanup
        if: ${{ always() }}
        run: bash clean.sh