name: Wipe Workflow Counter

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  actions: write
  contents: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wipe workflow counter
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git rm -f .github/workflow_counter.json
          git commit -a -m "Daily limit reset for $(date -d 'yesterday' +'%Y-%m-%d')"
          git push -f

      - name: Send a message to Telegram
        id: sendMessage
        run: |
          message="Daily limit reset for $(date -d 'yesterday' +'%Y-%m-%d')"
          response=$(curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="$message" \
            -d disable_notification=false)
          message_id=$(echo $response | jq -r '.result.message_id')
          echo "message_id=$message_id" >> $GITHUB_ENV
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/unpinChatMessage \
            -d chat_id=${{ secrets.CHAT_ID }}

      - name: Pin message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/pinChatMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d message_id=${{ env.message_id }} \
            -d disable_notification=false